# Generated by Django 5.1.6 on 2025-03-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.RemoveField(
            model_name='partners',
            name='image',
        ),
        migrations.AddField(
            model_name='partners',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners_main_images/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название партнёра'),
        ),
    ]
