# Generated by Django 5.1.6 on 2025-03-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events_images')),
                ('event_datetime', models.DateTimeField()),
            ],
        ),
    ]
