# Generated by Django 5.1.6 on 2025-03-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('active', 'Активныне'), ('completed', 'Завершенный')], default='active', max_length=10),
        ),
    ]
