# Generated by Django 5.1.6 on 2025-03-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_myevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='latitude',
            field=models.FloatField(default=55.7558),
        ),
        migrations.AddField(
            model_name='events',
            name='longitude',
            field=models.FloatField(default=37.6176),
        ),
    ]
