# Generated by Django 5.1.6 on 2025-03-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_events_latitude_events_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.TextField(default='Не указан'),
        ),
    ]
